export const site = {
  name: "403 Studio",
  tagline: "Anywhere. Anytime.",
  description:
    "Thoughtfully designed iPhone apps that are fast, reliable, and made to work wherever life takes you.",
  url: "https://www.403studio.ca",
  email: "hello@403studio.ca",
} as const;

export const apps = [
  {
    slug: "pilot-logbook",
    name: "Pilot Logbook",
    tagline: "Engineered for the flight deck.",
    description:
      "A comprehensive flight logger and duty tracker that works entirely offline — built to help Canadian pilots stay on top of their flight and duty time limits under the Canadian Aviation Regulations (CARs).",
    color: "blue" as const,
    icon: "/icon_pilot.jpg",
    iconDark: "/icon_pilot_dark.jpg",
    mockup: "/pilot_logbook_ui_v2.png",
    appStoreUrl: null,
    betaUrl: "https://testflight.apple.com/join/dbFtgJg6",
    websiteUrl: "https://pilotlogbook.ca",
    websiteLabel: "PilotLogbook.ca",
    syncDescription: "Exclusively for iPhone & iPad. Securely synchronized to PilotLogbook.ca. Your logbook, your data — encrypted and backed up to your private account.",
    features: [
      "Flight & Duty Logging: Track block, air, and duty times on the go",
      "Flight and Duty Limits: Monitor your duty periods against the CARs requirements and uses built-in alerts to warn you before you reach them",
      "Export Logs: Export logs to PDF and CSV formats ready for audits",
      "Scan Your Logbook: Digitize your paper logbooks and bring your history into one place",
      "Route Map & Stats: Interactive route mapping with insights into your most-flown routes",
      "Quick Logbook Entry: Fast, easy flight logging on your iPhone or iPad that syncs to your secure web dashboard",
      "Fleet Manager: Track aircraft details and most common types flown",
      "Document Expiry Tracker: Receive alerts for license, rating, and medical renewals",
      "Custom Log Fields: Tailor your entries to track specific flight or training hours",
      "100% Offline Capable: Log everything in the cockpit with zero cellular dependency — syncs automatically when you're back online",
    ],
  },
  {
    slug: "game-vault",
    name: "Game Vault - No Wi-Fi Games",
    tagline: "All the games you know and love — no Wi-Fi needed.",
    description:
      "Chess, checkers, tic-tac-toe, sudoku, and so many more classic games, all built for offline play. Perfect for long flights, subway commutes, or anywhere you lose signal. The timeless games you grew up with, plus a few originals we think you'll love.",
    color: "purple" as const,
    icon: "/icon_gamevault.png",
    iconDark: null,
    mockup: "/game_vault_mockup.png",
    appStoreUrl: null,
    betaUrl: "https://testflight.apple.com/join/zbA8DNVM",
    syncDescription: "For iPhone & iPad. Securely synchronized via your own personal iCloud.",
    screenshots: [
      { src: "/gv_vault_smash.jpg", alt: "Vault Smash game showing brick breaker style gameplay" },
    ],
    features: [
      "Chess, checkers, tic-tac-toe, sudoku & more",
      "Works offline — perfect for flights & commutes",
      "Daily challenges & XP progression system",
      "99 achievements & leaderboards to compete with your friends",
      "Secure iCloud synchronization",
      "Clean, beautiful interface for iPhone & iPad",
    ],
    games: [
      "Chess",
      "Checkers",
      "Tic-Tac-Toe",
      "4 in a Row",
      "Reversi",
      "Naval Strike",
      "Dots & Boxes",
      "Sudoku",
      "Minesweeper",
      "Vault 2048",
      "15 Puzzle",
      "Vault Solitaire",
      "Snake",
      "Memory Match",
      "Vault Smash",
      "Vault Jump",
      "Hangman",
      "Word Search"
    ],
  },
  {
    slug: "vegas-cyberpunk-midnight",
    name: "Vegas Cyberpunk Midnight",
    tagline: "The strip, in your pocket.",
    description:
      "A neon-drenched casino simulator packed with the classics — blackjack, roulette, plinko, slots, video poker, and baccarat. Built entirely for offline enjoyment with zero real money. Currently in active development.",
    color: "pink" as const,
    icon: "/icon_cyberpunk.png",
    iconDark: null,
    mockup: "/vegas_cyberpunk_mockup.png",
    appStoreUrl: null,
    betaUrl: null,
    syncDescription: "Exclusively for iPhone. Securely synchronized via your own personal iCloud.",
    screenshots: [
      { src: "/vcm_home.jpg", alt: "Vegas Cyberpunk Midnight home screen with all casino games" },
      { src: "/vcm_plinko.jpg", alt: "Plinko game with neon cyan aesthetics and multiplier slots" },
      { src: "/vcm_videopoker.jpg", alt: "Video Poker with Jacks or Better, Bonus, and Deuces modes" },
      { src: "/vcm_settings.jpg", alt: "Settings and achievements with level progression" },
      { src: "/vcm_splash.jpg", alt: "Vegas Cyberpunk Midnight splash screen" },
    ],
    features: [
      "Blackjack, plinko, slots, crash & more",
      "Fully offline casino experience",
      "No real money or gambling risk",
      "XP leveling & 13 unlockable achievements",
      "Sound effects, music & haptic feedback",
      "Cyberpunk-styled neon aesthetics for iPhone",
    ],
    games: [
      "Slots",
      "Plinko",
      "Blackjack",
      "Crash",
      "Video Poker",
      "Baccarat"
    ],
  },
] as const;
